// automation-lab/frontend-svelte/src/pages/LoginPage.svelte
<script>
  import { login } from '../stores/auth.svelte.js';
  import { navigateTo } from '../utils/navigation.js';

  export let onSuccess = () => {};
  export let redirectTo = '/';

  let email = '';
  let password = '';
  let loading = false;
  let error = '';

  const getRedirectTarget = () => {
    if (typeof window === 'undefined') return '/';

    const params = new URLSearchParams(window.location.search);
    const redirect = params.get('redirect');
    if (redirect && redirect.startsWith('/')) {
      return redirect;
    }

    return redirectTo;
  };

  const handleSubmit = async (event) => {
    event.preventDefault();
    loading = true;
    error = '';

    try {
      await login(email.trim(), password);
      onSuccess();
      navigateTo(getRedirectTarget());
    } catch (caughtError) {
      error = 'Credenciales inválidas. Intenta de nuevo.';
    } finally {
      loading = false;
    }
  };
</script>

<section class="login-shell" aria-labelledby="login-heading">
  <div class="login-card">
    <div class="login-hero">
      <span class="login-mark">NS</span>
      <h1 id="login-heading">Sign in</h1>
      <p>Use your email and password to continue.</p>
    </div>

    <form class="login-form" on:submit={handleSubmit}>
      <label>
        <span>Email</span>
        <input bind:value={email} type="email" name="email" autocomplete="email" required />
      </label>

      <label>
        <span>Password</span>
        <input bind:value={password} type="password" name="password" autocomplete="current-password" required />
      </label>

      {#if error}
        <p class="form-error" role="alert">{error}</p>
      {/if}

      <button type="submit" disabled={loading}>
        {loading ? 'Signing in...' : 'Enter'}
      </button>
    </form>
  </div>
</section>

<style>
  .login-shell {
    min-height: calc(100vh - 12rem);
    display: grid;
    place-items: center;
    padding: 2rem 0;
  }

  .login-card {
    width: min(100%, 460px);
    overflow: hidden;
    border-radius: 1.5rem;
    border: 1px solid rgba(15, 23, 42, 0.08);
    background: white;
    box-shadow: 0 14px 34px rgba(15, 23, 42, 0.08);
  }

  .login-hero {
    padding: 1.5rem;
    background: linear-gradient(135deg, #eff6ff, #e0f2fe);
  }

  .login-mark {
    display: inline-grid;
    place-items: center;
    width: 2.75rem;
    height: 2.75rem;
    border-radius: 0.9rem;
    background: #111827;
    color: white;
    font-weight: 800;
    margin-bottom: 1rem;
  }

  .login-hero h1 {
    margin: 0 0 0.45rem;
    color: #111827;
  }

  .login-hero p {
    margin: 0;
    color: #64748b;
    line-height: 1.6;
  }

  .login-form {
    display: grid;
    gap: 1rem;
    padding: 1.5rem;
  }

  label {
    display: grid;
    gap: 0.45rem;
    color: #334155;
    font-weight: 600;
  }

  input {
    width: 100%;
    border-radius: 0.9rem;
    border: 1px solid rgba(15, 23, 42, 0.14);
    padding: 0.85rem 0.95rem;
    background: #fff;
    color: #0f172a;
  }

  input:focus {
    outline: 2px solid rgba(59, 130, 246, 0.18);
    outline-offset: 2px;
  }

  .form-error {
    margin: 0;
    color: #b91c1c;
    background: #fef2f2;
    border: 1px solid #fecaca;
    border-radius: 0.8rem;
    padding: 0.7rem 0.85rem;
  }

  button {
    border: 0;
    border-radius: 0.95rem;
    padding: 0.9rem 1rem;
    background: #111827;
    color: white;
    font-weight: 700;
    cursor: pointer;
  }

  button:disabled {
    cursor: wait;
    opacity: 0.7;
  }
</style>

// automation-lab/frontend-angular/src/app/pages/login/login-page.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { Router, RouterModule } from '@angular/router';
import { authService } from '../../core/auth.service';

@Component({
  standalone: true,
  selector: 'login-page',
  imports: [CommonModule, FormsModule, RouterModule],
  template: `
    <section class="login-shell" [attr.data-testid]="'page-login'">
      <div class="login-card">
        <div class="login-hero">
          <span class="login-mark">RB</span>
          <h2>Bienvenido a Rabbit Bazaar</h2>
          <p>Ingresa con tus credenciales para continuar comprando.</p>
        </div>
        <form class="login-form" (ngSubmit)="submit()">
          <label>
            Email
            <input type="email" name="email" [(ngModel)]="email" [attr.data-testid]="'login-email'" required />
          </label>
          <label>
            Contraseña
            <input type="password" name="password" [(ngModel)]="password" [attr.data-testid]="'login-password'" required />
          </label>
          <button type="submit" [attr.data-testid]="'login-submit'">Entrar</button>
        </form>
      </div>
    </section>
  `,
  styles: [
    `.login-shell {
        min-height: calc(100vh - 90px);
        display: grid;
        place-items: center;
        padding: 60px 0;
      }
      .login-card {
        width: min(100%, 460px);
        background: var(--surface);
        border: 1px solid rgba(148,163,184,0.16);
        border-radius: 28px;
        box-shadow: var(--shadow);
        overflow: hidden;
      }
      .login-hero {
        padding: 32px 28px 24px;
        background: var(--accent-soft);
      }
      .login-mark {
        display: inline-flex;
        width: 44px;
        height: 44px;
        align-items: center;
        justify-content: center;
        border-radius: 16px;
        background: var(--accent);
        color: white;
        font-weight: 700;
        margin-bottom: 18px;
      }
      .login-hero h2 {
        margin: 0 0 8px;
        font-size: 1.6rem;
      }
      .login-hero p {
        margin: 0;
        color: var(--muted);
      }
      .login-form {
        display: grid;
        gap: 18px;
        padding: 28px;
      }
      label {
        display: grid;
        gap: 8px;
        font-weight: 600;
        color: var(--text);
      }
      input {
        width: 100%;
        border: 1px solid rgba(148,163,184,0.24);
        border-radius: 16px;
        padding: 14px 16px;
        background: var(--surface-strong);
        color: var(--text);
      }
      input:focus {
        border-color: rgba(79,70,229,0.3);
      }
      button {
        width: 100%;
        padding: 14px 18px;
        border-radius: 16px;
        background: var(--accent);
        color: white;
        font-weight: 700;
        box-shadow: 0 14px 24px rgba(79,70,229,0.14);
      }
      button:hover {
        background: #4338ca;
      }
    `],
})
export class LoginPage {
  email = '';
  password = '';
  constructor(private router: Router) {}

  async submit() {
    try {
      await authService.login(this.email, this.password);
      this.router.navigate(['/']);
    } catch (e) {
      alert('Credenciales inválidas');
    }
  }
}
